### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by unknownghost401** [Christynorl/php-joern-test#1]
i ddin't saw any of your social media profiles to ping u ... thats why im here ...

i wanna know more about the report that you've written in huntr.dev https://huntr.dev/bounties/f66d33df-6588-4ab4-80a0-847451517944/

please respond if you're seeing this .. TY

**Comment by Christynorl** [comment]
Hi, @unknownghost401  . I'd be happy to explain this report to you, it's about xss vulnerabilities in pdf files. Our web service provides users with the function of loading and previewing pdf files before users download pdf files. We can embed javascript code in pdf files, and other users will receive xss attacks when previewing our pdf files. For more details, please refer to the following report [report](https://owasp.org/www-pdf-archive/OWASP_IL_The_Universal_XSS_PDF_Vulnerability.pdf)
If you have other questions or cooperation, you can also consult me.

**Comment by unknownghost401** [comment]
is there any way to make an alert document.cookie or document.domain or any redirection to malicious pages ? 
asking this coz it has no relation with the DOM!

i'm a noob .. nd im asking for possibilities about the Redirection !

please , im expecting an answer ..
im a student  : )

**Comment by Christynorl** [comment]
> is there any way to make an alert document.cookie or document.domain or any redirection to malicious pages ? asking this coz it has no relation with the DOM!
> 
> i'm a noob .. nd im asking for possibilities about the Redirection !
> 
> please , im expecting an answer .. im a student : )

I regret to inform you that there is currently no way to execute the document command through a PDF file. You can only use this method to pop up advertisements or attempt CSRF vulnerabilities
